name: Publish wiki
on:
  push:
  schedule:
    - cron: "*/5 * * * *"

concurrency:
  group: wiki
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  sync_files:
     runs-on: ubuntu-latest
     steps:
       - name: Git checkout
         uses: actions/checkout@v4
       - name: Run GitHub File Sync
         uses: BetaHuhn/repo-file-sync-action@v1
         with:
           GH_PAT: ${{ secrets.GH_PAT }}
  wiki:
    needs: sync_files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: spenserblack/actions-wiki@main

