name: Publish wiki
on:
  push:
  schedule:
    - cron: "*/5 * * * *"

concurrency:
  group: wiki
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  sync_files:
     runs-on: ubuntu-latest
     steps:
       - name: Git checkout
         uses: actions/checkout@v4
       - name: File Sync
         uses: netlify/file-sync-action@main
         with:
           files: '{"knerio/javautils#README.md": ".github/wiki/Home.md"}'
           token: ${{ secrets.GITHUB_TOKEN }}
  wiki:
    needs: sync_files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: spenserblack/actions-wiki@main

