name: Publish wiki
on:
  push:
  schedule:
    - cron: "*/5 * * * *"

concurrency:
  group: wiki
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: spenserblack/actions-wiki@main
